
[package]
name = "poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana_rbpf = { git = "https://github.com/windowhan/custom_rbpf", branch = "main" }
trace = "*"
debug_print = "*"